language:
- python
python:
- '3.4'
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: zKwoOYJ1lN0h5819PFSntf5l1Hgqy0DzMKPfVlphFEH3GJcYTh6vD4Tfr5OCm2vPyHsseIkkaQbJ5sbItB9GatHQH31tv0OTTSesFso4bI3xRwc1yMOYazfG/2GTUGn/AHriAGqy5gVjuBlzwWixqeGQB0fUFQ6qmHIVWdVubwwxOHuvqVc5tbzfnJ41vFU73+/sx7AuWcJmlSW5W4PjQWg+KzbSsE6yyLL6b7Tqe/BnbMPFvpq55kCCd4URDyA3ARXC8k1QUnWABsxRudp6DG4fsWNBNdAcTMRN1WokVikObbWEYuEPm6zFnCSnhtpPLAbQGMExc5BknrHkML4pGU6cJfnIUqLdkwngAqdaeArLVSr11HgmLQcRLQRN5t/9YxxOaWRJhIe+cA29bQXgpons2mox44gZRHR9aZ8tIcMcuvV0M84Fj4kCUj31atM1d4Z9MEnvZoiGsivpkOFdx9HFIYJI+873daYJrNFPPtzyRiIhhr4OERIZIY3W/OB0a6wTGN1Jncwn8gArXNsGIWGxULpR1AuluoBUk2eOMhswZE7Cvf89LfJCTXy5r13dkPNQLe/ix6lE2CwPPl2ZqIoz3gBhtuXmDWBgJsN1ZavcO7pL5VAluv1UyOEcFGCoahB0zzvWGTSFlbZBZB2j3KvxuM/PgpJri5tlQFOZ9b4=
  app: whispering-mountain-62274
  on:
    branch: master
    python: '3.4'
    repo: jcue/flasktaskr
    
